apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-security-rules
  namespace: system-workloads
data:
  rules.yaml: |
    - rule: Privileged Container Started
      desc: Detect privileged container execution
      condition: container.privileged=true
      output: Privileged container started (user=%user.name pod=%k8s.pod.name)
      priority: CRITICAL

    - rule: Write below etc
      desc: Detect writes to /etc
      condition: evt.type in (open,openat) and fd.name startswith /etc
      output: Write to /etc detected (user=%user.name pod=%k8s.pod.name)
      priority: WARNING
