checks:
  addAllBuiltIn: true
  exclude:
    - "unset-memory-requirements"
    - "unset-cpu-requirements"

customChecks:
  - name: no-privileged-containers
    template: privileged-container
    params:
      forbidden: true
