apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: default-seccomp-profile
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: add-seccomp
      match:
        any:
          - resources:
              kinds: ["Pod"]
      mutate:
        patchStrategicMerge:
          spec:
            securityContext:
              seccompProfile:
                type: RuntimeDefault
