apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    verbs: ["create", "update", "patch", "delete"]
    resources:
      - group: ""
        resources: ["pods", "secrets", "configmaps"]
  - level: RequestResponse
    users: ["system:serviceaccount:kube-system:replicaset-controller"]
  - level: None
    resources:
      - group: ""
        resources: ["events"]
