apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: break-glass-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: break-glass-admin-binding
subjects:
  - kind: User
    name: break-glass-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: break-glass-admin
  apiGroup: rbac.authorization.k8s.io
