apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-reader
  namespace: user-workloads
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-writer
  namespace: user-workloads
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete"]
