apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: runtime-security-mutating
webhooks:
  - name: enforce-security-context.security.platform
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    clientConfig:
      service:
        name: security-admission
        namespace: system-workloads
        path: /mutate
    timeoutSeconds: 5
